kind: Secret
apiVersion: v1
metadata:
  name: ibm-entitlement-key
data:
  .dockerconfigjson: >-
     eyJhdXRocyI6eyJjcC5pY3IuaW8iOnsidXNlcm5hbWUiOiJjcCIsInBhc3N3b3JkIjoiZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUpKUWswZ1RXRnlhMlYwY0d4aFkyVWlMQ0pwWVhRaU9qRTJNakkzTlRBM056a3NJbXAwYVNJNkltUTBNRFl3TmpSaVptTmtaRFJrTVdWaVptWTJNbVZpWVdWbVlqVmlPRGN4SW4wLkIwMUpLUnZ2M1hEa0FRQnNIbldRc09rcGVQZjBlUlhPLWUwVHJhaHZIRzgiLCJhdXRoIjoiWTNBNlpYbEthR0pIWTJsUGFVcEpWWHBKTVU1cFNqa3VaWGxLY0dNelRXbFBhVXBLVVdzd1oxUlhSbmxoTWxZd1kwZDRhRmt5VldsTVEwcHdXVmhSYVU5cVJUSk5ha2t6VGxSQk0wNTZhM05KYlhBd1lWTkpOa2x0VVRCTlJGbDNUbXBTYVZwdFRtdGFSRkpyVFZkV2FWcHRXVEpOYlZacFdWZFdiVmxxVm1sUFJHTjRTVzR3TGtJd01VcExVbloyTTFoRWEwRlJRbk5JYmxkUmMwOXJjR1ZRWmpCbFVsaFBMV1V3VkhKaGFIWklSemdLIiwiZW1haWwiOiIifX19Cg==
type: kubernetes.io/dockerconfigjson
