apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: was-pipeline-run-
spec:

  params:
  - name: APP_NAME
    value: mod-resorts
  - name: APP_VERSION
    value: '1.0'
  - name: DEPLOY_PROJECT
    value: 'was-liberty'
  - name: GIT_URL
    value: 'https://github.com/bpaskin/WASLiberty-Tekton'
  - name: MAX_PODS
    value: '5'

  serviceAccountName: pipeline

  pipelineRef:
    name: was-pipeline

  workspaces:
  - name: maven-settings
    persistentVolumeClaim:
       claimName: was-pipeline-pvc

  - name: shared-workspace
    persistentVolumeClaim:
       claimName: was-pipeline-pvc
