kind: Secret
apiVersion: v1
metadata:
  name: github-user-pass 
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://myuser:mytoken@github.com
